### ISSUE TITLE
Search Modal

### ISSUE THREAD

**Issue by rickywid** [projectunic0rn/foundit-ui#34]
Create Search Modal on Landing Page

**DESKTOP**
https://app.zeplin.io/project/5c4bf56f4762f57a98a2f587/screen/5c5515acb74a4430818e5d3a
**MOBILE**
https://app.zeplin.io/project/5c4bf56f4762f57a98a2f587/screen/5c5515ad31131d309f06479d

**Comment by StratoDuck** [comment]
@rickywid I've looked a bit into it, is there gonna be more than one use for this modal? Or just in the landing page? 
If so, then it should be part of the landing page after issue #33 is done.
